### ISSUE TITLE
services are not starting after reboot

### ISSUE THREAD

**Issue by charbelsarkis** [bmork/defogger#2]
Hello, 
First of all great work!

I am using firmware v2.02.02, and followed the instructions successfully.  No errors were logged during the process.

however, after building and uploading the customer firmware fw.tar, the camera restarts but lighttpd and telnetd do not start automatically.

Any hints?
Thanks!

**Comment by bmork** [comment]
Sorry to hear it didn't work.  Since you had success with the initial Bluetooth, I'd suggest you use it to enable telnetd temporarily again.  Then log in with admin/"pincode" and see if you can figure out what went wrong.

My gut feeling is that the flashing procedure failed. Run 
`mount | grep opt
`and/or 
`ls -l /opt
`and see if there is anything there at all.  Probably not....

I don't really have a quick fix for that.  Trying the firmware upgrade a second time is worth a shot.It might work.  If that doesn't help, then you can upload the  squashfs generated as part of the fw.tar build and write it manually to the partition using for example 
`cat  opt.squashfs >/dev/mtdblock2
`

**Comment by charbelsarkis** [comment]
Thanks, let me see what I can do....

**Comment by charbelsarkis** [comment]
Ok so just to confirm, I manually wrote the partition "cat opt.squashfs >/dev/mtdblock2" and now it survives the boot.

Password is set and httpd starts at boot.

Thanks again for the great work!
Charbel

**Comment by tz3000** [comment]
Hi, I also have this issue.
Thanks for your excellent code, everything works smoothly except over restart. `mount | grep opt` and `ls -l /opt` returns nothing (I'm assuming that means that there isn't anything in the aforementioned directory)
I'm not sure I fully understand the "quick fix". Should I first upload the squashfs file (If this is the case, where do I find this?) or is running the ` cat opt.squashfs >/dev/mtdblock2 ` command through telnet sufficient for keeping the services running?
Thanks.

**Comment by tz3000** [comment]
Hello again, Issue solved!

For future reference:

1. Setup a tftp server, place the `opt.squashfs` file generated earlier in the shared directory
2. Telnet into camera (as per instructions)
3. cd to tmp: 
`# cd tmp`
4. Upload the file via tftp:
`# tftp -g -r opt.squashfs *IP of server*`
5. Run the `cat opt.squashfs >/dev/mtdblock2` command:
`# cat opt.squashfs >/dev/mtdblock2`
6. Exit telnet and then restart the camera.
`# exit`

Everything persists over restart.
Thanks for your excellent code! You made this camera worth using.
